name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  CI_Pipeline:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: indraneelartham/sudokusolver:latest

  CD_Pipeline:
    name: Pull Docker image to EC2 and Run
    runs-on: ubuntu-latest
    needs: CI_Pipeline
    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop sudoku_solver || true
            docker rm sudoku_solver || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sudokusolver
            docker run -d --name sudoku_solver -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/sudokusolver

